//
//  Generated file. Do not edit.
//

#import <Flutter/Flutter.h>

/**
 * This file is generated by the Flutter tool based on the
 * plugins that support the platform channel-based plugin APIs.
 * You should not edit this file, but rather add and remove plugins
 * from `pubspec.yaml` and then run `flutter pub get`.
 */

@interface GeneratedPluginRegistrant : NSObject
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry;
@end